# Generated by Django 3.1.5 on 2021-03-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elegislative_app', '0033_remove_olddocumentsmodel_last_modified_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioRecording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='audio/%Y/%m/%d')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('remarks', models.CharField(max_length=250)),
                ('size', models.CharField(max_length=250)),
                ('length', models.CharField(max_length=250)),
                ('date_uploaded', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
