# Generated by Django 3.1.5 on 2021-07-14 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elegislative_app', '0035_orderofbusiness'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False)),
                ('time_triggered', models.DateTimeField(auto_now=True)),
                ('date_filed', models.DateTimeField(auto_now_add=True)),
                ('attendance_user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_user_fk', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
