# Generated by Django 3.1.5 on 2021-07-14 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elegislative_app', '0036_attendance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendance',
            new_name='AttendanceModel',
        ),
    ]
