# Generated by Django 3.1.5 on 2021-07-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elegislative_app', '0037_auto_20210714_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancemodel',
            name='date_filed',
            field=models.DateField(auto_now_add=True),
        ),
    ]
